# Generated by Django 4.2.14 on 2024-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_logintable_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logintable',
        ),
        migrations.DeleteModel(
            name='userprofile',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
